// <auto-generated />
using System;
using BeautySalonExpolorer.DAL.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BeautySalonExpolorer.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260526152553_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BeautySalonExpolorer.DAL.Entities.Business", b =>
                {
                    b.Property<Guid>("BusinessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("business_id");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("district");

                    b.Property<string>("LocationUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("location_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("decimal(2,1)")
                        .HasColumnName("rating");

                    b.Property<int?>("ReviewsCount")
                        .HasColumnType("integer")
                        .HasColumnName("reviews_count");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("street");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("website");

                    b.HasKey("BusinessId")
                        .HasName("pk_business");

                    b.ToTable("business", (string)null);
                });

            modelBuilder.Entity("BeautySalonExpolorer.DAL.Entities.BusinessCategory", b =>
                {
                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.HasKey("BusinessId", "CategoryId")
                        .HasName("pk_businesscategory");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_businesscategory_category_id");

                    b.ToTable("businesscategory", (string)null);
                });

            modelBuilder.Entity("BeautySalonExpolorer.DAL.Entities.BusinessService", b =>
                {
                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_id");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.HasKey("BusinessId", "ServiceId")
                        .HasName("pk_businessservice");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_businessservice_service_id");

                    b.ToTable("businessservice", (string)null);
                });

            modelBuilder.Entity("BeautySalonExpolorer.DAL.Entities.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("CategoryId")
                        .HasName("pk_category");

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("BeautySalonExpolorer.DAL.Entities.Service", b =>
                {
                    b.Property<Guid>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("ServiceId")
                        .HasName("pk_service");

                    b.ToTable("service", (string)null);
                });

            modelBuilder.Entity("BeautySalonExpolorer.DAL.Entities.BusinessCategory", b =>
                {
                    b.HasOne("BeautySalonExpolorer.DAL.Entities.Business", "Business")
                        .WithMany("Categories")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_businesscategory_business_business_id");

                    b.HasOne("BeautySalonExpolorer.DAL.Entities.Category", "Category")
                        .WithMany("Businesses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_businesscategory_categories_category_id");

                    b.Navigation("Business");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BeautySalonExpolorer.DAL.Entities.BusinessService", b =>
                {
                    b.HasOne("BeautySalonExpolorer.DAL.Entities.Business", "Business")
                        .WithMany("Services")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_businessservice_business_business_id");

                    b.HasOne("BeautySalonExpolorer.DAL.Entities.Service", "Service")
                        .WithMany("Businesses")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_businessservice_services_service_id");

                    b.Navigation("Business");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("BeautySalonExpolorer.DAL.Entities.Business", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("BeautySalonExpolorer.DAL.Entities.Category", b =>
                {
                    b.Navigation("Businesses");
                });

            modelBuilder.Entity("BeautySalonExpolorer.DAL.Entities.Service", b =>
                {
                    b.Navigation("Businesses");
                });
#pragma warning restore 612, 618
        }
    }
}
