// <auto-generated />
using System;
using BeautySalonExpolorer.DAL.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BeautySalonExpolorer.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BeautySalonExpolorer.DAL.Entities.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("CategoryId")
                        .HasName("pk_category");

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("BeautySalonExpolorer.DAL.Entities.Salon", b =>
                {
                    b.Property<Guid>("SalonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("salon_id");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("district");

                    b.Property<string>("LocationUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("location_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("decimal(2,1)")
                        .HasColumnName("rating");

                    b.Property<int?>("ReviewsCount")
                        .HasColumnType("integer")
                        .HasColumnName("reviews_count");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("street");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("website");

                    b.HasKey("SalonId")
                        .HasName("pk_salon");

                    b.ToTable("salon", (string)null);
                });

            modelBuilder.Entity("BeautySalonExpolorer.DAL.Entities.SalonCategory", b =>
                {
                    b.Property<Guid>("SalonId")
                        .HasColumnType("uuid")
                        .HasColumnName("salon_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.HasKey("SalonId", "CategoryId")
                        .HasName("pk_saloncategory");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_saloncategory_category_id");

                    b.ToTable("saloncategory", (string)null);
                });

            modelBuilder.Entity("BeautySalonExpolorer.DAL.Entities.SalonService", b =>
                {
                    b.Property<Guid>("SalonId")
                        .HasColumnType("uuid")
                        .HasColumnName("salon_id");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.HasKey("SalonId", "ServiceId")
                        .HasName("pk_salonservice");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_salonservice_service_id");

                    b.ToTable("salonservice", (string)null);
                });

            modelBuilder.Entity("BeautySalonExpolorer.DAL.Entities.Service", b =>
                {
                    b.Property<Guid>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("ServiceId")
                        .HasName("pk_service");

                    b.ToTable("service", (string)null);
                });

            modelBuilder.Entity("BeautySalonExpolorer.DAL.Entities.SalonCategory", b =>
                {
                    b.HasOne("BeautySalonExpolorer.DAL.Entities.Category", "Category")
                        .WithMany("Salons")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_saloncategory_category_category_id");

                    b.HasOne("BeautySalonExpolorer.DAL.Entities.Salon", "Salon")
                        .WithMany("Categories")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_saloncategory_salon_salon_id");

                    b.Navigation("Category");

                    b.Navigation("Salon");
                });

            modelBuilder.Entity("BeautySalonExpolorer.DAL.Entities.SalonService", b =>
                {
                    b.HasOne("BeautySalonExpolorer.DAL.Entities.Salon", "Salon")
                        .WithMany("Services")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_salonservice_salon_salon_id");

                    b.HasOne("BeautySalonExpolorer.DAL.Entities.Service", "Service")
                        .WithMany("Salons")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_salonservice_services_service_id");

                    b.Navigation("Salon");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("BeautySalonExpolorer.DAL.Entities.Category", b =>
                {
                    b.Navigation("Salons");
                });

            modelBuilder.Entity("BeautySalonExpolorer.DAL.Entities.Salon", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("BeautySalonExpolorer.DAL.Entities.Service", b =>
                {
                    b.Navigation("Salons");
                });
#pragma warning restore 612, 618
        }
    }
}
